Script started on 2022年02月22日 星期二 21时38分12秒
]0;yuanw28@zuma:hw4[yuanw28@zuma hw4]$ make
gcc -ansi -std=c99 -Wall -c PhotoLab.c -o PhotoLab.o
gcc -ansi -std=c99 -Wall -c FileIO.c -o FileIO.o
gcc -ansi -std=c99 -Wall -c Image.c -o Image.o
gcc -ansi -std=c99 -Wall -c Test.c -o Test.o
gcc -ansi -std=c99 -Wall -c  DIPs.c -o DIPs.o
gcc -ansi -std=c99 -Wall -c Advanced.c -o Advanced.o
ar rc libFilter.a Advanced.o DIPs.o
ranlib libFilter.a
gcc -ansi -std=c99 -Wall -lm PhotoLab.o FileIO.o Image.o Test.o -L. -lFilter -o PhotoLab
gcc -ansi -std=c99 -Wall -c -DDEBUG -g -c PhotoLab.c -o PhotoLabTest.o
gcc -ansi -std=c99 -Wall -c -DDEBUG -g Test.c -o Test_DEBUG.o
gcc -ansi -std=c99 -Wall -lm PhotoLabTest.o FileIO.o Image.o Test_DEBUG.o -L. -lFilter -o PhotoLabTest
]0;yuanw28@zuma:hw4[yuanw28@zuma hw4]$ ./PhotoLab

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
10: Add border to an image
11: Add Noise to an image
12: Sharpen the image
13: Posterize the image
14: Blur the image
15: Crop an image
16: Resize an image
17: Adjust the Brightness and Contrast of an image
18: Add Watermark to an image
19: Test all functions
20: Exit
Please make your choice: 19
AutoTest finished successfully.

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
10: Add border to an image
11: Add Noise to an image
12: Sharpen the image
13: Posterize the image
14: Blur the image
15: Crop an image
16: Resize an image
17: Adjust the Brightness and Contrast of an image
18: Add Watermark to an image
19: Test all functions
20: Exit
Please make your choice: 20
You exit the program.
]0;yuanw28@zuma:hw4[yuanw28@zuma hw4]$ valgrind --leak-check=full ./PhotoLabTest
==2039== Memcheck, a memory error detector
==2039== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==2039== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==2039== Command: ./PhotoLabTest
==2039== 
==2039== 
==2039== HEAP SUMMARY:
==2039==     in use at exit: 0 bytes in 0 blocks
==2039==   total heap usage: 0 allocs, 0 frees, 0 bytes allocated
==2039== 
==2039== All heap blocks were freed -- no leaks are possible
==2039== 
==2039== For counts of detected and suppressed errors, rerun with: -v
==2039== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 8 from 6)
]0;yuanw28@zuma:hw4[yuanw28@zuma hw4]$ make clean
rm -f *.o *.jpg PhotoLab PhotoLabTest bw.ppm edge.ppm shuffle.ppm brightness.ppm hmirror.ppm hue.ppm bigresize.ppm smallresize.ppm rotate.ppm rotater.ppm saturate.ppm hflip.ppm libFilter.a
]0;yuanw28@zuma:hw4[yuanw28@zuma hw4]$ exit
exit

Script done on 2022年02月22日 星期二 21时38分51秒
