Script started on 2022年02月07日 星期一 23时24分46秒
]0;yuanw28@zuma:hw3[yuanw28@zuma hw3]$ make clean
rm -f *.o
rm -f PhotoLab
rm -f PhotoLabTest
]0;yuanw28@zuma:hw3[yuanw28@zuma hw3]$ make
gcc -c -Wall -ansi -std=c11 PhotoLab.c -o PhotoLab.o
gcc -c -Wall -ansi -std=c11 FileIO.c -o FileIO.o
gcc -c -Wall -ansi -std=c11 DIPs.c -o DIPs.o
gcc -c -Wall -ansi -std=c11 Advanced.c -o Advanced.o
ar rc libfilter.a DIPs.o Advanced.o
ranlib libfilter.a
gcc -lm -Wall -ansi -std=c11 PhotoLab.o FileIO.o -L. -lfilter -o PhotoLab
gcc -c -DDEBUG -Wall -ansi -std=c11 PhotoLab.c -o PhotoLabTest.o
gcc -lm -Wall -ansi -std=c11 PhotoLabTest.o FileIO.o -L. -lfilter -o PhotoLabTest
]0;yuanw28@zuma:hw3[yuanw28@zuma hw3]$ ./PhotoLab

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
10: Add border to an image
11: Add Noise to an image
12: Sharpen the image
13: Posterize the image
14: Blur the image
15: Test all functions
16: Exit
Please make your choice: 15
EngPlaza.ppm was read.
bw.ppm was saved. 
bw.jpg was stored.
EngPlaza.ppm was read.
negative.ppm was saved. 
negative.jpg was stored.
EngPlaza.ppm was read.
colorfilter.ppm was saved. 
colorfilter.jpg was stored.
EngPlaza.ppm was read.
edge.ppm was saved. 
edge.jpg was stored.
EngPlaza.ppm was read.
vmirror.ppm was saved. 
vmirror.jpg was stored.
EngPlaza.ppm was read.
vflip.ppm was saved. 
vflip.jpg was stored.
EngPlaza.ppm was read.
shuffle.ppm was saved. 
shuffle.jpg was stored.
EngPlaza.ppm was read.
border.ppm was saved. 
border.jpg was stored.
EngPlaza.ppm was read.
noise.ppm was saved. 
noise.jpg was stored.
EngPlaza.ppm was read.
sharpen.ppm was saved. 
sharpen.jpg was stored.
EngPlaza.ppm was read.
posterize.ppm was saved. 
posterize.jpg was stored.
EngPlaza.ppm was read.
motion_blur.ppm was saved. 
motion_blur.jpg was stored.

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
10: Add border to an image
11: Add Noise to an image
12: Sharpen the image
13: Posterize the image
14: Blur the image
15: Test all functions
16: Exit
Please make your choice: 16
You exit the program.
]0;yuanw28@zuma:hw3[yuanw28@zuma hw3]$ exis[K[Kit
exit

Script done on 2022年02月07日 星期一 23时25分07秒
